### ISSUE TITLE
Поле post всегда пустое 

### ISSUE THREAD

**Issue by antonshevelev** [pozitronik/yii2-exceptionslogger#15]
В поле post всегда записывается пустой массив

**Comment by pozitronik** [comment]
Не подтверждаю, вот тест: https://github.com/pozitronik/yii2-exceptionslogger/blob/master/tests/Functional/RequestParamsCest.php#L60

**Comment by pozitronik** [comment]
Несмотря на то, что не воспроизводится, нужно поменять обращение к `$_POST` на `Yii::$app->request->post()`

**Comment by pozitronik** [comment]
Should be fixed
