### ISSUE TITLE
Добавить возможность настраивать отображаемые колонки в таблице в index экшене

### ISSUE THREAD

**Issue by Ilyxa-777** [pozitronik/yii2-exceptionslogger#3]
При подключении модуля в настройках добавить возможность задавать названия полей из таблицы sys_exceptions
которые необходимо выводить в таблице в разделе index.

**Comment by pozitronik** [comment]
Это решается через [yii2-grid-config](https://github.com/pozitronik/yii2-grid-config/), но я не хочу добавлять эту зависимость, потому что она требует дополнительной миграции. Но я могу сделать возможность переопределять каталог к вьюхам, как это сделано в [yii2-references](https://github.com/pozitronik/yii2-references/), например. Тогда можно будет написать альтернативные вьюхи и в конфиге их подсунуть.
Устроит такое решение?

**Comment by Ilyxa-777** [comment]
да

**Comment by pozitronik** [comment]
web.php:

```php
'modules' => [
	'sysexceptions' => [
		'class' => SysExceptionsModule::class,
		'params' => [
			'viewPath' => '@app/views/exceptions',
		],
		...
	],
]
```
